<?php
/**
 * Dedicated file editor workspace.
 *
 * The page is opened in a new tab from the file manager. The server still
 * authorizes every read and save API request; query parameters only select
 * the initial workspace and file.
 */
declare(strict_types=1);
require_once __DIR__ . '/../../php/db.php';
secureSession();
if (empty($_SESSION['email'])) { header('Location: /login'); exit; }
$subdomain = cleanInput((string)($_GET['subdomain'] ?? ''));
$file = ltrim(str_replace('\\','/',(string)($_GET['file'] ?? '')), '/');
if ($subdomain === '' || $file === '') { http_response_code(400); exit('A workspace and file are required.'); }
?>
<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Editor · <?php echo htmlspecialchars($file); ?> · NodeXGo</title><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"><link rel="stylesheet" href="https://unpkg.com/grapesjs/dist/css/grapes.min.css"><link rel="stylesheet" href="https://releases.transloadit.com/uppy/v4.13.3/uppy.min.css"><style>body{background:#07152f;color:#eaf3ff;font-family:DM Sans,system-ui,sans-serif}.editor-topbar{background:#0b1e43;border-bottom:1px solid rgba(255,255,255,.12)}.editor-main{height:calc(100vh - 66px)}.editor-sidebar{width:260px;background:#0b1e43;border-right:1px solid rgba(255,255,255,.1)}.editor-canvas{min-width:0;background:#f1f5f9}.editor-canvas textarea{height:calc(100vh - 150px);resize:none;background:#081429;color:#d9efff;border:0;border-radius:0;font:14px/1.6 ui-monospace,SFMono-Regular,Menlo,monospace}.editor-canvas .gjs-editor{height:calc(100vh - 150px)}#gjs{height:calc(100vh - 150px);background:white}.editor-tab{border:0;border-radius:.6rem;color:#9bb0cc;background:transparent}.editor-tab.active{background:#0d6efd;color:#fff}.btn-info{background:#42e8ff;border-color:#42e8ff}.file-meta{font-size:.75rem;color:#9bb0cc;word-break:break-all}@media(max-width:767.98px){.editor-sidebar{width:64px}.editor-sidebar .sidebar-label,.editor-sidebar .file-meta{display:none}.editor-sidebar .btn{font-size:0}.editor-sidebar .btn i{font-size:1rem}.editor-topbar .file-title{max-width:150px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}}</style></head><body>
<header class="editor-topbar p-2"><div class="container-fluid d-flex align-items-center justify-content-between gap-2"><div class="d-flex align-items-center gap-2"><a href="javascript:history.back()" class="btn btn-sm btn-outline-light rounded-pill"><i class="fa-solid fa-arrow-left"></i><span class="d-none d-sm-inline ms-1">Back</span></a><strong class="file-title">Editing: <?php echo htmlspecialchars($file); ?></strong></div><div class="d-flex gap-2"><button class="btn btn-sm btn-info fw-bold" id="saveEditor"><i class="fa-solid fa-floppy-disk me-1"></i><span class="d-none d-sm-inline">Save</span></button><button class="btn btn-sm btn-outline-light" id="previewEditor"><i class="fa-solid fa-eye me-1"></i><span class="d-none d-sm-inline">Preview</span></button></div></div></header>
<main class="editor-main d-flex"><aside class="editor-sidebar p-2 p-md-3 d-flex flex-column gap-2"><div class="sidebar-label text-uppercase small text-white-50 mb-2">Workspace tools</div><button class="btn btn-outline-light text-start" id="modeCode"><i class="fa-solid fa-code me-2"></i><span class="sidebar-label">Code editor</span></button><button class="btn btn-outline-light text-start" id="modeVisual"><i class="fa-solid fa-wand-magic-sparkles me-2"></i><span class="sidebar-label">GrapesJS board</span></button><button class="btn btn-outline-light text-start" id="uploadEditorFile"><i class="fa-solid fa-upload me-2"></i><span class="sidebar-label">Upload asset</span></button><button class="btn btn-outline-light text-start" id="reloadEditor"><i class="fa-solid fa-rotate me-2"></i><span class="sidebar-label">Reload file</span></button><div class="mt-auto file-meta"><i class="fa-solid fa-folder-open me-1"></i><?php echo htmlspecialchars($subdomain); ?><br><i class="fa-solid fa-file-code me-1"></i><?php echo htmlspecialchars($file); ?></div></aside><section class="editor-canvas flex-grow-1 position-relative"><textarea id="codeEditor" spellcheck="false" aria-label="Source code editor"></textarea><div id="gjs" class="d-none"></div><input id="editorUpload" type="file" class="d-none" multiple></section></main>
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script><script src="https://unpkg.com/grapesjs"></script><script src="https://releases.transloadit.com/uppy/v4.13.3/uppy.min.js"></script><script>
const workspace=<?php echo json_encode($subdomain, JSON_UNESCAPED_SLASHES); ?>, filePath=<?php echo json_encode($file, JSON_UNESCAPED_SLASHES); ?>; let editor=null, code='';
const toast=(message,icon='info')=>Swal.fire({toast:true,position:'top-end',timer:3000,showConfirmButton:false,icon,title:message});
function loadFile(){ $.getJSON('/api/files/read',{subdomain:workspace,file:filePath}).done(res=>{if(!res.success)return toast(res.message,'error'); code=res.content||''; $('#codeEditor').val(code); if(editor){editor.setComponents(code);}}).fail(()=>toast('Unable to load this file.','error')); }
function visualMode(){ $('#codeEditor').addClass('d-none'); $('#gjs').removeClass('d-none'); if(!editor){editor=grapesjs.init({container:'#gjs',height:'100%',width:'auto',storageManager:false,panels:{defaults:[]},blockManager:{appendTo:'#gjs'}});} editor.setComponents($('#codeEditor').val()||''); $('#modeVisual').addClass('active'); $('#modeCode').removeClass('active'); }
function codeMode(){ if(editor){const html=editor.getHtml(),css=editor.getCss();$('#codeEditor').val(css?'<style>\\n'+css+'\\n</style>\\n'+html:html);} $('#gjs').addClass('d-none');$('#codeEditor').removeClass('d-none');$('#modeCode').addClass('active');$('#modeVisual').removeClass('active'); }
$('#modeCode').on('click',codeMode);$('#modeVisual').on('click',visualMode);$('#reloadEditor').on('click',loadFile);$('#saveEditor').on('click',()=>{let content=$('#codeEditor').val();if(editor&&!$('#gjs').hasClass('d-none')){const html=editor.getHtml(),css=editor.getCss();content=css?'<style>\\n'+css+'\\n</style>\\n'+html:html;}$.post('/api/files/save',{subdomain:workspace,file:filePath,content},res=>{res.success?toast('File saved successfully.','success'):toast(res.message||'Save failed.','error');},'json').fail(()=>toast('Save request failed.','error'));});$('#previewEditor').on('click',()=>window.open('/site/'+encodeURIComponent(workspace)+'/','_blank','noopener'));$('#uploadEditorFile').on('click',()=>$('#editorUpload').trigger('click'));$('#editorUpload').on('change',function(){const fd=new FormData();fd.append('subdomain',workspace);fd.append('path',filePath.split('/').slice(0,-1).join('/'));Array.from(this.files).forEach(f=>fd.append('file[]',f));$.ajax({url:'/api/files/upload',method:'POST',data:fd,contentType:false,processData:false,dataType:'json'}).done(res=>toast(res.message,res.success?'success':'error')).fail(()=>toast('Asset upload failed.','error'));});loadFile();codeMode();
</script></body></html>
