<?php
/**
 * NodeXGo public homepage.
 *
 * Rebuild contract: this file owns only the public presentation layer. The
 * central router, session logic, tenant routing, API contracts, payments,
 * and secure services remain unchanged. Every section is intentionally
 * commented so future maintainers can safely edit the narrative without
 * accidentally modifying application logic.
 */
declare(strict_types=1);
require_once __DIR__ . '/../../php/db.php';
?>
<!doctype html>
<html lang="en">
<head>
  <?= renderSeoHead(['title'=>'NodeXGo | Engineering Africa\'s technology future','description'=>'NodeXGo builds modular software, space-data intelligence, and creative technology platforms for ambitious teams.','og_title'=>'NodeXGo | Engineering Africa\'s technology future','og_description'=>'Explore the NodeXGo corporate mission, founder mandate, portfolio, roadmap, traction, and workspace platform.','images'=>['/assets/images/generated/nodexgo-deep-space-hero-final.png','/main/assets/images/cedar-profile.jpg'],'og_type'=>'website','schema_type'=>'WebSite']) ?>
  <meta name="theme-color" content="#050a1c">
  <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Space+Grotesk:wght@500;600;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/aos@2.3.4/dist/aos.css">
  <link rel="stylesheet" href="/assets/css/landing-pro.css?v=20260820-rebuild23">
</head>
<body>
<?php require_once __DIR__ . '/../modul/nav.html'; ?>
<main>
<!-- 01. Hero: establishes the deep-space visual language and primary action. -->
<section class="nx-hero section-dark nx-final-hero" id="home"><div class="container position-relative"><div class="row align-items-center g-5"><div class="col-lg-6" data-aos="fade-up"><span class="eyebrow"><i class="fa-solid fa-satellite me-2"></i>EARTH, CLOUD, ORBITAL DATA, AND CODE</span><h1 class="display-2 fw-bold mt-3">Engineering Africa's<br><span class="text-gradient">technology future.</span></h1><p class="lead text-white-50 mt-4 mb-4">NodeXGo deploys lightweight modular software, space-data intelligence, and creative digital platforms that help ambitious teams move from idea to impact.</p><div class="d-flex flex-wrap gap-3"><a href="/register" class="btn btn-info btn-lg rounded-pill px-4 fw-bold text-dark">Create your workspace <i class="fa-solid fa-arrow-right ms-2"></i></a><a href="#about" class="btn btn-outline-light btn-lg rounded-pill px-4">Explore our story</a></div></div><div class="col-lg-6" data-aos="zoom-in"><div class="hero-art"><img src="/assets/images/generated/nodexgo-deep-space-hero-final.png" alt="3D blue orbital NodeXGo platform cube" class="img-fluid"><span class="float-chip chip-one"><i class="fa-solid fa-satellite text-info me-2"></i>Earth to stars</span><span class="float-chip chip-two"><i class="fa-solid fa-code text-info me-2"></i>Modular by design</span></div></div></div></div></section>
<!-- 02. Metrics: concise proof points for the operating model. -->
<section class="nx-section nx-metrics"><div class="container"><div class="row g-3 text-center"><div class="col-6 col-lg-3"><div class="metric-card"><strong>23</strong><span>public narrative sections</span></div></div><div class="col-6 col-lg-3"><div class="metric-card"><strong>1</strong><span>single-entry platform core</span></div></div><div class="col-6 col-lg-3"><div class="metric-card"><strong>99.99%</strong><span>uptime target</span></div></div><div class="col-6 col-lg-3"><div class="metric-card"><strong>24/7</strong><span>workspace availability</span></div></div></div></div></section>
<!-- 03. About: the corporate mission remains the source narrative. -->
<section class="nx-section" id="about"><div class="container"><div class="row align-items-center g-5"><div class="col-lg-6" data-aos="fade-right"><span class="eyebrow eyebrow-dark">03 / ABOUT CORPORATE</span><h2 class="display-6 fw-bold mt-3">Pure, lightweight architecture for maximum speed and simplicity.</h2><p class="text-secondary mt-4">NodeXGo exists to bridge cloud computation with orbital research and useful creative technology. We aim to dismantle unnecessary environment overhead and give emerging startups and enterprise teams dependable modular platforms.</p><p class="text-secondary">Our file-based, single-entry approach keeps the core understandable, portable, and fast while still providing secure tenant isolation, dashboards, subscriptions, and production workflows.</p><div class="d-flex flex-wrap gap-3 mt-4"><a href="/about" class="btn btn-dark rounded-pill px-4">Read the full corporate story</a><a href="/cedar" class="btn btn-outline-dark rounded-pill px-4">Meet the founder</a></div></div><div class="col-lg-6" data-aos="fade-left"><div class="row g-3"><div class="col-6"><img class="img-fluid rounded-4 nx-visual" src="/main/assets/images/about-banner-1.jpg" alt="NodeXGo team collaborating on technology solutions"></div><div class="col-6 pt-5"><img class="img-fluid rounded-4 nx-visual" src="/main/assets/images/about-banner-2.jpg" alt="NodeXGo orbital telemetry research environment"></div></div></div></div></div></section>
<!-- 04. Founder: existing Cedar image and founder mandate. -->
<section class="nx-profile-banner section-dark" id="cedar"><div class="container"><div class="row align-items-center g-5"><div class="col-lg-4 text-center" data-aos="zoom-in"><img src="/main/assets/images/cedar-profile.jpg" class="img-fluid rounded-circle nx-profile-art" alt="Cedar Anyanwu, Founder, CEO and Systems Architect"></div><div class="col-lg-8" data-aos="fade-left"><span class="eyebrow">04 / FOUNDER MANDATE</span><h2 class="display-6 fw-bold mt-3">Cedar Anyanwu</h2><p class="text-info fw-bold">Founder, CEO &amp; Systems Architect</p><p class="text-white-50 mt-3">Cedar directs NodeXGo's corporate growth trajectory and system architecture. With more than a decade of experience designing lightweight modular software frameworks, remote-sensing downlinks, and high-performance server pipelines, he leads the company toward practical technology adoption.</p><blockquote class="border-start border-info border-3 ps-3 text-white fst-italic">“African startups should not be burdened by heavy subscription overhead or complex database administration.”</blockquote><p class="text-white-50">Under Cedar's vision, orbital metrics, soil moisture, deforestation, and land-tracking data become more accessible to African research teams and developers through streamlined API channels.</p><a href="/cedar" class="btn btn-light text-dark rounded-pill px-4 mt-2">Read Cedar's full mandate <i class="fa-solid fa-arrow-right ms-2"></i></a></div></div></div></section>
<!-- 05. Principles: explains the design and engineering standards. -->
<section class="nx-section nx-soft" id="principles"><div class="container"><div class="text-center mb-5"><span class="eyebrow eyebrow-dark">05 / PRINCIPLES</span><h2 class="display-6 fw-bold mt-2">A platform shaped by useful constraints.</h2><p class="text-secondary mx-auto" style="max-width:720px">The rebuild keeps the system legible, secure, portable, and respectful of the teams who operate it.</p></div><div class="row g-4"><div class="col-md-4"><article class="nx-card h-100"><div class="icon-box"><i class="fa-solid fa-feather-pointed"></i></div><h3>Lean by default</h3><p>Clear PHP boundaries, modular assets, and a focused dependency surface keep the platform understandable.</p></article></div><div class="col-md-4"><article class="nx-card h-100"><div class="icon-box"><i class="fa-solid fa-shield-halved"></i></div><h3>Secure by contract</h3><p>Role checks, workspace boundaries, protected routes, and server-side verification remain non-negotiable.</p></article></div><div class="col-md-4"><article class="nx-card h-100"><div class="icon-box"><i class="fa-solid fa-compass-drafting"></i></div><h3>Built to evolve</h3><p>Public storytelling and secure operations share a visual system without sharing unsafe application responsibilities.</p></article></div></div></div></section>
<!-- 06. Portfolio: executive systems and preserved portfolio route. -->
<section class="nx-section" id="portfolio"><div class="container"><div class="text-center mb-5"><span class="eyebrow eyebrow-dark">06 / EXECUTIVE PORTFOLIO</span><h2 class="display-6 fw-bold mt-2">Systems built for real operating environments.</h2><p class="text-secondary">Explore the strategic digital deployments behind the NodeXGo direction.</p></div><div class="row g-4"><div class="col-md-4"><article class="nx-card h-100"><div class="icon-box"><i class="fa-solid fa-route"></i></div><h3>Modular CMS Router</h3><p>A single-entry routing engine enabling subdomains, CMS widgets, isolated local schemas, and tenant websites.</p><a href="/portfolio">View executive portfolio <i class="fa-solid fa-arrow-right ms-1"></i></a></article></div><div class="col-md-4"><article class="nx-card h-100"><div class="icon-box"><i class="fa-solid fa-earth-africa"></i></div><h3>GIS Imagery Processing</h3><p>Satellite land telemetry is downlinked and processed into soil-quality and environmental insights.</p><a href="/portfolio">Explore space technology <i class="fa-solid fa-arrow-right ms-1"></i></a></article></div><div class="col-md-4"><article class="nx-card h-100"><div class="icon-box"><i class="fa-solid fa-clapperboard"></i></div><h3>Creative Digital Systems</h3><p>White-label dashboards, media operations, and modular website experiences help creators build durable operations.</p><a href="/gallary">See the gallery <i class="fa-solid fa-arrow-right ms-1"></i></a></article></div></div></div></section>
<!-- 07. Roadmap: public direction and preserved roadmap route. -->
<section class="nx-section nx-soft" id="roadmap"><div class="container"><div class="row align-items-center g-5"><div class="col-lg-5"><span class="eyebrow eyebrow-dark">07 / CORPORATE ROADMAP</span><h2 class="display-6 fw-bold mt-3">A structured path from foundation to scale.</h2><p class="text-secondary mt-3">Our roadmap connects the native platform engine, media yield automation, and agritech telemetry into a clear direction.</p><a href="/roadmap" class="btn btn-dark rounded-pill px-4 mt-2">Read the full roadmap</a></div><div class="col-lg-7"><div class="timeline"><div class="timeline-item"><span>Q1–Q2 2026</span><div><h3>Foundation Engine</h3><p>Full deployment of the native multi-tenant PHP router with local JSON data stores and modular architecture.</p></div></div><div class="timeline-item"><span>Q3–Q4 2026</span><div><h3>Platform Scale</h3><p>Media and ad-yield automation, browser agents, and tracking tools for creators and media studios.</p></div></div><div class="timeline-item"><span>Next horizon</span><div><h3>Telemetry and partnerships</h3><p>Wider access to spatial data, research workflows, and useful technology alliances.</p></div></div></div></div></div></div></section>
<!-- 08. Traction: measurable system outcomes. -->
<section class="nx-image-section section-dark" id="traction"><div class="container"><div class="row align-items-center g-5"><div class="col-lg-6 order-lg-2"><img class="img-fluid rounded-5 nx-visual" src="/assets/images/generated/nodexgo-data-3d.png" alt="3D data intelligence globe representing NodeXGo traction"></div><div class="col-lg-6 order-lg-1"><span class="eyebrow">08 / PLATFORM TRACTION</span><h2 class="display-6 fw-bold mt-3">Traction measured in useful systems.</h2><p class="text-white-50 mt-3">Our spatial telemetry maps track agricultural soil-health metrics across regional farms, while the modular single-entry platform handles active requests with a strong uptime target.</p><div class="row g-3 mt-4"><div class="col-6"><div class="mini-stat"><strong>35%+</strong><span>Reported yield improvement in supported agricultural models</span></div></div><div class="col-6"><div class="mini-stat"><strong>99.99%</strong><span>Platform uptime target for modular operations</span></div></div></div><a href="/traction" class="btn btn-light text-dark rounded-pill px-4 mt-4">Explore platform traction</a></div></div></div></section>
<!-- 09. Gallery: original corporate images remain available. -->
<section class="nx-section" id="gallery"><div class="container"><div class="row justify-content-between align-items-end mb-5"><div class="col-lg-7"><span class="eyebrow eyebrow-dark">09 / CORPORATE GALLERY</span><h2 class="display-6 fw-bold mt-2">A visual record of the work.</h2><p class="text-secondary">Space telemetry, agritech maps, team craft, and the platform interfaces that connect the pieces.</p></div><div class="col-lg-3 text-lg-end"><a href="/gallary" class="btn btn-outline-dark rounded-pill">Open full gallery</a></div></div><div class="row g-3"><div class="col-md-6"><img class="img-fluid rounded-4 gallery-img" src="/main/assets/images/about-team-1.jpg" alt="NodeXGo software operations team"></div><div class="col-md-3"><img class="img-fluid rounded-4 gallery-img" src="/main/assets/images/about-team-2.jpg" alt="NodeXGo satellite telemetry analysis team"></div><div class="col-md-3"><img class="img-fluid rounded-4 gallery-img" src="/main/assets/images/about-team-3.jpg" alt="NodeXGo user experience engineering team"></div></div></div></section>
<!-- 10. Workspace: the tenant product in one clear view. -->
<section class="nx-section nx-soft" id="platform"><div class="container"><div class="row align-items-center g-5"><div class="col-lg-6"><img class="img-fluid rounded-5 nx-visual" src="/assets/images/generated/nodexgo-orbit-platform-final.png" alt="3D NodeXGo website builder and code workspace"></div><div class="col-lg-6"><span class="eyebrow eyebrow-dark">10 / WORKSPACE PLATFORM</span><h2 class="display-6 fw-bold mt-3">Design it visually. Refine it in code. Publish it as your own.</h2><p class="text-secondary mt-3">Create a tenant website with a subdomain-first public link, manage files securely, work in the code editor, and open a dedicated GrapesJS workspace.</p><div class="d-flex flex-wrap gap-2 mt-4"><span class="tool-pill">Bootstrap</span><span class="tool-pill">GrapesJS</span><span class="tool-pill">File manager</span><span class="tool-pill">Flutterwave</span></div><a href="/register" class="btn btn-primary rounded-pill px-4 mt-4">Start building</a></div></div></div></section>
<!-- 11. Security: public promise tied to secure routes. -->
<section class="nx-section section-dark" id="security"><div class="container"><div class="text-center mb-5"><span class="eyebrow">11 / TRUSTED OPERATIONS</span><h2 class="display-6 fw-bold mt-3">Security should feel like confidence.</h2><p class="text-white-50 mx-auto" style="max-width:680px">Profiles, tenant isolation, protected roles, verified payments, and bounded file operations keep sensitive work in the right hands.</p></div><div class="row g-4"><div class="col-md-4"><div class="nx-dark-card h-100"><i class="fa-solid fa-user-shield"></i><h3>Identity first</h3><p>Role-aware dashboards, profile controls, and immutable super-admin protection.</p></div></div><div class="col-md-4"><div class="nx-dark-card h-100"><i class="fa-solid fa-folder-tree"></i><h3>Workspace boundaries</h3><p>File operations remain bounded to the authorized tenant workspace.</p></div></div><div class="col-md-4"><div class="nx-dark-card h-100"><i class="fa-solid fa-credit-card"></i><h3>Verified subscriptions</h3><p>Flutterwave checkout and server-side confirmation protect the upgrade flow.</p></div></div></div></div></section>
<!-- 12. Tenant websites: subdomain-first publishing explanation. -->
<section class="nx-section" id="tenants"><div class="container"><div class="row g-5 align-items-center"><div class="col-lg-6"><span class="eyebrow eyebrow-dark">12 / TENANT WEBSITES</span><h2 class="display-6 fw-bold mt-3">Your site gets a real home on the platform.</h2><p class="text-secondary mt-3">When a user creates a website, NodeXGo generates a link such as <strong>myblog.nodexplatform.com.ng</strong> and resolves it through the single entry point.</p><div class="domain-preview mt-4"><span>https://</span><strong>myblog</strong><span>.nodexplatform.com.ng</span></div></div><div class="col-lg-6"><div class="nx-card dark-edge"><i class="fa-solid fa-globe icon-large"></i><h3>Subdomain-first routing</h3><p>Tenant resolution remains separate from public application pages and is enforced before workspace data is served.</p><a href="/register" class="btn btn-dark rounded-pill px-4">Create a tenant site</a></div></div></div></div></section>
<!-- 13. File manager: secure workspace capability. -->
<section class="nx-section nx-soft" id="files"><div class="container"><div class="text-center mb-5"><span class="eyebrow eyebrow-dark">13 / FILE MANAGER</span><h2 class="display-6 fw-bold mt-2">A workspace for every asset.</h2><p class="text-secondary">Upload ZIP projects, extract safely, copy, move, rename, edit, and organize files inside the authorized workspace boundary.</p></div><div class="row g-4"><div class="col-md-3"><div class="feature-tile"><i class="fa-solid fa-file-zipper"></i><h3>ZIP extraction</h3><p>Safe archive handling with traversal protection.</p></div></div><div class="col-md-3"><div class="feature-tile"><i class="fa-solid fa-arrows-up-down-left-right"></i><h3>Move and copy</h3><p>Organize project files without leaving the workspace.</p></div></div><div class="col-md-3"><div class="feature-tile"><i class="fa-solid fa-pen-to-square"></i><h3>Code editing</h3><p>Read and save supported text and code files.</p></div></div><div class="col-md-3"><div class="feature-tile"><i class="fa-solid fa-wand-magic-sparkles"></i><h3>Visual editing</h3><p>Open selected pages in the full GrapesJS workspace.</p></div></div></div></div></section>
<!-- 14. GrapesJS: visual editor path. -->
<section class="nx-section" id="editor"><div class="container"><div class="row align-items-center g-5"><div class="col-lg-5"><img class="img-fluid rounded-5 nx-visual" src="/assets/images/generated/nodexgo-orbit-platform-final.png" alt="NodeXGo visual editor workspace"></div><div class="col-lg-7"><span class="eyebrow eyebrow-dark">14 / VISUAL EDITOR</span><h2 class="display-6 fw-bold mt-3">Move from file tree to visual canvas.</h2><p class="text-secondary mt-3">Click a supported file, open the editor in a full-screen window, and refine HTML/CSS in a focused visual environment. The existing editor route and selected-file query contract remain unchanged.</p><a href="/register" class="btn btn-outline-dark rounded-pill px-4 mt-3">Open a workspace</a></div></div></div></section>
<!-- 15. Plans: pricing entry points. -->
<section class="nx-section nx-soft" id="plans"><div class="container"><div class="text-center mb-5"><span class="eyebrow eyebrow-dark">15 / PLANS</span><h2 class="display-6 fw-bold mt-2">Start focused. Scale when ready.</h2><p class="text-secondary">Choose a clear starting point and upgrade through the secure dashboard.</p></div><div class="row g-4"><div class="col-md-4"><div class="plan-card h-100"><span class="plan-label">Launch</span><h3>Starter</h3><p>Basic hosting and a focused starting workspace.</p><div class="plan-price">₦3,000 <small>/ month</small></div><a href="/register" class="btn btn-outline-dark rounded-pill w-100 mt-4">Choose Launch</a></div></div><div class="col-md-4"><div class="plan-card featured h-100"><span class="badge bg-info text-dark rounded-pill mb-3">Most popular</span><span class="plan-label">Momentum</span><h3>Business</h3><p>Full web, workspace, and analytics operations.</p><div class="plan-price">₦75,000 <small>/ month</small></div><a href="/register" class="btn btn-info text-dark rounded-pill w-100 mt-4 fw-bold">Choose Momentum</a></div></div><div class="col-md-4"><div class="plan-card h-100"><span class="plan-label">Scale</span><h3>Enterprise</h3><p>Custom infrastructure and space-data partnership.</p><div class="plan-price">Custom <small>plan</small></div><a href="mailto:hello@nodexplatform.com.ng" class="btn btn-outline-dark rounded-pill w-100 mt-4">Talk to us</a></div></div></div></div></section>
<!-- 16. Payments: explains the subscription activation contract. -->
<section class="nx-section" id="payments"><div class="container"><div class="row g-5 align-items-center"><div class="col-lg-7"><span class="eyebrow eyebrow-dark">16 / FLUTTERWAVE UPGRADES</span><h2 class="display-6 fw-bold mt-3">A payment flow designed for verified activation.</h2><p class="text-secondary mt-3">Subscriptions and upgrades begin in the dashboard and are activated only after server-side Flutterwave verification. Secret keys remain in environment configuration rather than public templates.</p><div class="d-flex gap-3 flex-wrap mt-4"><span class="tool-pill"><i class="fa-solid fa-lock me-2"></i>Server verified</span><span class="tool-pill"><i class="fa-solid fa-receipt me-2"></i>Receipt aware</span><span class="tool-pill"><i class="fa-solid fa-rotate me-2"></i>Callback safe</span></div></div><div class="col-lg-5"><div class="payment-card"><i class="fa-solid fa-credit-card"></i><strong>Secure upgrade path</strong><span>Initialize → Pay → Verify → Activate</span></div></div></div></div></section>
<!-- 17. Profiles: user and admin identity controls. -->
<section class="nx-section nx-soft" id="profiles"><div class="container"><div class="text-center mb-5"><span class="eyebrow eyebrow-dark">17 / PROFILES</span><h2 class="display-6 fw-bold mt-2">Identity that works across the platform.</h2><p class="text-secondary">Users and administrators can manage profile images, account details, passwords, and role-aware sessions through secure pages.</p></div><div class="row g-4"><div class="col-md-6"><div class="nx-card h-100"><i class="fa-solid fa-id-card icon-large"></i><h3>User profile workspace</h3><p>Keep account settings and tenant activity in one clear, responsive place.</p><a href="/login">Sign in to manage your profile</a></div></div><div class="col-md-6"><div class="nx-card h-100"><i class="fa-solid fa-user-tie icon-large"></i><h3>Administrator controls</h3><p>Privileged views expose only the tools allowed by the active role and permissions.</p><a href="/login">Open secure access</a></div></div></div></div></section>
<!-- 18. Company story: links to the preserved narrative pages. -->
<section class="nx-section" id="story"><div class="container"><div class="row align-items-center g-5"><div class="col-lg-6"><span class="eyebrow eyebrow-dark">18 / COMPANY STORY</span><h2 class="display-6 fw-bold mt-3">The platform is part of a larger direction.</h2><p class="text-secondary mt-3">Read the original public narratives to understand the people, portfolio, roadmap, traction, and creative systems that inform NodeXGo.</p></div><div class="col-lg-6"><div class="story-links"><a href="/about"><span>About NodeXGo</span><i class="fa-solid fa-arrow-right"></i></a><a href="/cedar"><span>Cedar's mandate</span><i class="fa-solid fa-arrow-right"></i></a><a href="/portfolio"><span>Executive portfolio</span><i class="fa-solid fa-arrow-right"></i></a><a href="/gallary"><span>Corporate gallery</span><i class="fa-solid fa-arrow-right"></i></a></div></div></div></div></section>
<!-- 19. FAQ: onboarding questions. -->
<section class="nx-section nx-soft" id="faq"><div class="container"><div class="row justify-content-center"><div class="col-lg-9"><div class="text-center mb-5"><span class="eyebrow eyebrow-dark">19 / QUESTIONS</span><h2 class="display-6 fw-bold mt-2">A clearer way to get started.</h2></div><div class="accordion nx-accordion" id="nxFaq"><div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#faqOne">Can I launch a public tenant website?</button></h3><div id="faqOne" class="accordion-collapse collapse show" data-bs-parent="#nxFaq"><div class="accordion-body">Yes. A created site receives a link such as <strong>myblog.nodexplatform.com.ng</strong> and is served through the single entry point.</div></div></div><div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faqTwo">Can I manage code and visual pages?</button></h3><div id="faqTwo" class="accordion-collapse collapse" data-bs-parent="#nxFaq"><div class="accordion-body">Yes. The secure file manager can open supported files in the code editor or dedicated GrapesJS route.</div></div></div><div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faqThree">How do subscriptions work?</button></h3><div id="faqThree" class="accordion-collapse collapse" data-bs-parent="#nxFaq"><div class="accordion-body">Subscriptions and upgrades are initialized through Flutterwave and activated only after server-side verification.</div></div></div></div></div></div></div></section>
<!-- 20. Contact: direct support and partnership path. -->
<section class="nx-section" id="contact"><div class="container"><div class="contact-panel"><div><span class="eyebrow eyebrow-dark">20 / CONTACT</span><h2 class="display-6 fw-bold mt-3">Bring the hard problem.</h2><p class="text-secondary mb-0">Tell NodeXGo what you are building, what data you need, or where your current stack is slowing you down.</p></div><a href="mailto:hello@nodexplatform.com.ng" class="btn btn-dark btn-lg rounded-pill px-4">hello@nodexplatform.com.ng</a></div></div></section>
<!-- 21. Enterprise: partnership and custom infrastructure invitation. -->
<section class="nx-section section-dark" id="enterprise"><div class="container text-center"><span class="eyebrow">21 / ENTERPRISE DIRECTION</span><h2 class="display-6 fw-bold mt-3">Build a durable operating layer.</h2><p class="text-white-50 mx-auto mt-3" style="max-width:700px">For research teams, media organizations, agritech partners, and enterprise operators, NodeXGo can shape a custom platform path around secure modular foundations.</p><a href="mailto:hello@nodexplatform.com.ng" class="btn btn-light text-dark rounded-pill px-4 mt-3">Discuss an enterprise path</a></div></section>
<!-- 22. Final CTA: last conversion point before the footer. -->
<section class="nx-cta" id="cta"><div class="container"><div class="nx-cta-inner text-center"><span class="eyebrow eyebrow-dark">22 / YOUR NEXT MOVE</span><h2 class="display-5 fw-bold mt-3">Give your next idea a better place to grow.</h2><p class="text-secondary mx-auto mt-3">Build the site. Organize the work. Keep moving with a platform shaped by software, space data, and African ambition.</p><div class="d-flex flex-wrap justify-content-center gap-3 mt-4"><a href="/register" class="btn btn-dark btn-lg rounded-pill px-4">Start your workspace</a><a href="/login" class="btn btn-outline-dark btn-lg rounded-pill px-4">Open secure access</a></div></div></div></section>
<!-- 23. Public navigation: a final route index makes the full public system discoverable. -->
<section class="nx-section nx-soft" id="public-navigation"><div class="container"><div class="row g-4 align-items-center"><div class="col-lg-5"><span class="eyebrow eyebrow-dark">23 / PUBLIC NAVIGATION</span><h2 class="display-6 fw-bold mt-3">Everything connected. Nothing hidden.</h2><p class="text-secondary mb-0">Use the public route index to move from the company story into secure workspace access without losing context.</p></div><div class="col-lg-7"><div class="row g-2"><div class="col-6 col-md-3"><a class="btn btn-outline-dark rounded-pill w-100" href="/about">About</a></div><div class="col-6 col-md-3"><a class="btn btn-outline-dark rounded-pill w-100" href="/cedar">Cedar</a></div><div class="col-6 col-md-3"><a class="btn btn-outline-dark rounded-pill w-100" href="/portfolio">Portfolio</a></div><div class="col-6 col-md-3"><a class="btn btn-outline-dark rounded-pill w-100" href="/roadmap">Roadmap</a></div><div class="col-6 col-md-3"><a class="btn btn-outline-dark rounded-pill w-100" href="/traction">Traction</a></div><div class="col-6 col-md-3"><a class="btn btn-outline-dark rounded-pill w-100" href="/gallary">Gallery</a></div><div class="col-6 col-md-3"><a class="btn btn-dark rounded-pill w-100" href="/login">Login</a></div><div class="col-6 col-md-3"><a class="btn btn-info text-dark rounded-pill w-100 fw-bold" href="/register">Register</a></div></div></div></div></div></section>
</main>
<!-- Footer: public navigation, legal surface, and company identity. -->
<footer class="nx-footer" id="footer"><div class="container"><div class="row g-4 justify-content-between"><div class="col-lg-4"><a class="navbar-brand d-flex align-items-center gap-2 text-white" href="/"><img src="/main/assets/images/logo.png?v=production" alt="NodeXGo logo" class="nx-brand-logo"><span>nodex<span class="text-info">Go</span></span></a><p class="text-white-50 small mt-3">Deploying enterprise web architectures, remote-sensing telemetry networks, and white-label modular PHP ecosystems.</p></div><div class="col-6 col-lg-2"><h4>Company</h4><a href="#about">About</a><a href="#cedar">Founder</a><a href="/portfolio">Portfolio</a><a href="/gallary">Gallery</a></div><div class="col-6 col-lg-2"><h4>Direction</h4><a href="/roadmap">Roadmap</a><a href="/traction">Traction</a><a href="/about">Mission</a><a href="/login">Workspace login</a></div><div class="col-lg-3"><h4>Build with us</h4><a href="/register">Deploy new tenant</a><a href="/cms/admin">Code-first CMS</a><a href="mailto:hello@nodexplatform.com.ng">hello@nodexplatform.com.ng</a></div></div><hr class="border-secondary my-4"><div class="d-flex flex-column flex-md-row justify-content-between gap-2 small text-white-50"><span>© <?= date('Y') ?> NodeXGo. All rights reserved.</span><span>Software · Space data · Creative systems</span></div></div></footer>
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script><script src="https://cdn.jsdelivr.net/npm/aos@2.3.4/dist/aos.js"></script><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script><script>AOS.init({duration:700,once:true,offset:80});</script>
</body></html>
