<?php
/**
 * Deep-space public registration presentation.
 * The registration contract remains unchanged: #registerForm submits to
 * /php/register.php using the existing fullname, email, and password fields.
 */
declare(strict_types=1);
require_once __DIR__ . '/../../php/db.php';
secureSession();
?><!doctype html>
<html lang="en"><head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Deploy Tenant | NodeXGo</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Space+Grotesk:wght@500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="/assets/css/public-space.css?v=20260820"><link rel="stylesheet" href="/assets/css/nx-secure.css?v=20260820">
</head><body class="nx-public-space">
<div class="nx-space-stars"></div>
<?php require_once __DIR__ . '/../modul/nav.html'; ?>
<main class="nx-auth-shell"><div class="container"><div class="nx-auth-panel row g-0 align-items-stretch mx-auto" style="max-width:1120px">
<section class="nx-auth-copy col-lg-6 d-flex flex-column justify-content-center"><span class="eyebrow text-info fw-bold small"><i class="fa-solid fa-rocket me-2"></i>DEPLOY A NEW NODE</span><h1 class="mt-3">Your next idea<br><span class="text-info">starts in orbit.</span></h1><p class="mt-4">Create your NodeXGo workspace, launch a tenant website, and move from a blank page to a polished public presence with secure tools built into the platform.</p><div class="row g-2 mt-3"><div class="col-6"><div class="p-3 rounded-4 border border-secondary-subtle bg-dark bg-opacity-50"><i class="fa-solid fa-globe text-info mb-2"></i><div class="small fw-bold">Public subdomain</div><div class="small text-white-50">myblog.nodexplatform.com.ng</div></div></div><div class="col-6"><div class="p-3 rounded-4 border border-secondary-subtle bg-dark bg-opacity-50"><i class="fa-solid fa-wand-magic-sparkles text-info mb-2"></i><div class="small fw-bold">Visual builder</div><div class="small text-white-50">GrapesJS ready</div></div></div></div><img class="nx-auth-visual" src="/assets/images/generated/nodexgo-orbit-platform-final.png" alt="3D NodeXGo website builder visual"></section>
<section class="nx-auth-form col-lg-6"><div class="text-center mb-4"><img src="/main/assets/images/logo.png?v=production" alt="NodeXGo logo" style="height:48px;width:auto" class="mb-3"><h2>Deploy your workspace</h2><p class="text-secondary mb-0">Initialize your isolated tenant portal</p></div><div id="alertBox" class="alert d-none" role="alert"></div><form id="registerForm" novalidate><div class="mb-3 text-start"><label class="form-label" for="regFullname">FULL NAME</label><div class="input-group"><span class="input-group-text"><i class="fa-solid fa-user"></i></span><input type="text" id="regFullname" class="form-control" placeholder="Amina Anyanwu" autocomplete="name" required></div></div><div class="mb-3 text-start"><label class="form-label" for="regEmail">EMAIL ADDRESS</label><div class="input-group"><span class="input-group-text"><i class="fa-solid fa-envelope"></i></span><input type="email" id="regEmail" class="form-control" placeholder="user@domain.com" autocomplete="email" required></div></div><div class="mb-4 text-start"><label class="form-label" for="regPassword">PASSWORD</label><div class="input-group"><span class="input-group-text"><i class="fa-solid fa-key"></i></span><input type="password" id="regPassword" class="form-control" placeholder="Create a secure password" autocomplete="new-password" minlength="8" required></div><div class="form-text">Use at least eight characters for a stronger workspace account.</div></div><button type="submit" id="btnRegister" class="btn btn-premium w-100"><i class="fa-solid fa-circle-plus me-2"></i>Initialize account</button></form><div class="text-center border-top mt-4 pt-4"><p class="small text-secondary mb-0">Already have an account? <a href="/login" class="fw-bold text-decoration-none">Sign in to your workspace</a></p></div></section>
</div></div></main>
<?php require_once __DIR__ . '/../modul/footer.html'; ?>
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script><script src="/assets/js/nx-feedback.js"></script>
<script>
$(function(){
  $('#registerForm').on('submit',function(e){e.preventDefault();const alertBox=$('#alertBox'),btn=$('#btnRegister');if(!this.checkValidity()){this.classList.add('was-validated');return;}btn.prop('disabled',true).html('<i class="fa-solid fa-spinner fa-spin me-2"></i>Initializing...');alertBox.addClass('d-none').removeClass('alert-success alert-danger');$.ajax({url:'/php/register.php',type:'POST',dataType:'json',data:{fullname:$('#regFullname').val(),email:$('#regEmail').val(),password:$('#regPassword').val()},success:function(r){btn.prop('disabled',false).html('<i class="fa-solid fa-user-check me-2"></i>Initialize account');alertBox.removeClass('d-none');if(r.success===true){alertBox.addClass('alert-success').html('<i class="fa-solid fa-envelope-circle-check me-1"></i> '+r.message);$('#registerForm')[0].reset();}else{alertBox.addClass('alert-danger').html('<i class="fa-solid fa-triangle-exclamation me-1"></i> '+r.message);}},error:function(xhr){btn.prop('disabled',false).html('<i class="fa-solid fa-user-check me-2"></i>Initialize account');const r=xhr.responseJSON||{};alertBox.removeClass('d-none').addClass('alert-danger').html('<i class="fa-solid fa-triangle-exclamation me-1"></i> '+(r.message||'Server communication error. Please try again.'));}});});
});
</script></body></html>
