<?php
/**
 * Responsive tenant profile tab.
 *
 * The dashboard controller processes the POST requests. This view is kept
 * presentation-focused so it can be reused in the SPA and direct dashboard.
 */
$tabId = 'profile';
if (!isset($dashboardContext)) { $requestedTab = $tabId; require_once __DIR__ . '/../dashboard.php'; exit; }
$profileAvatar = trim((string)($user['avatar'] ?? ''));
?>
<div id="profile" class="tab-section <?php echo ($activeTab === 'profile') ? 'active-tab' : ''; ?>">
  <div class="row g-4">
    <div class="col-12 col-lg-4"><div class="card border-0 shadow-sm rounded-4 h-100"><div class="card-body text-center p-4"><div class="mb-3" id="profileAvatarPreview"><?php if($profileAvatar): ?><img src="<?php echo htmlspecialchars($profileAvatar); ?>" class="rounded-circle object-fit-cover" style="width:128px;height:128px" alt="Your profile picture"><?php else: ?><div class="rounded-circle bg-primary text-white d-inline-flex align-items-center justify-content-center fw-bold" style="width:128px;height:128px;font-size:3.25rem"><?php echo htmlspecialchars(strtoupper(substr((string)$user['fullname'],0,1))); ?></div><?php endif; ?></div><h1 class="h5 fw-bold mb-1"><?php echo htmlspecialchars((string)$user['fullname']); ?></h1><p class="text-muted small mb-2"><?php echo htmlspecialchars((string)$user['email']); ?></p><span class="badge text-bg-primary text-uppercase"><?php echo htmlspecialchars(str_replace('_',' ',(string)($user['role'] ?? 'tenant'))); ?></span><hr><dl class="row text-start small mb-0"><dt class="col-5">Status</dt><dd class="col-7"><?php echo htmlspecialchars((string)($user['status'] ?? 'active')); ?></dd><dt class="col-5">Joined</dt><dd class="col-7"><?php echo htmlspecialchars((string)($user['created_at'] ?? '-')); ?></dd><dt class="col-5">Subscription</dt><dd class="col-7"><?php echo htmlspecialchars((string)($subscriptionStatus ?? 'trial')); ?></dd></dl></div></div></div>
    <div class="col-12 col-lg-8"><div class="card border-0 shadow-sm rounded-4 mb-4"><div class="card-body p-3 p-md-4"><h2 class="h6 fw-bold mb-3"><i class="fa-solid fa-id-card text-primary me-2"></i>Profile details</h2><form action="/user/dashboard#profile" method="POST" enctype="multipart/form-data" class="row g-3" novalidate><input type="hidden" name="csrf" value="<?php echo htmlspecialchars($_SESSION['profile_csrf'] ?? ''); ?>"><input type="hidden" name="action" value="update_profile"><div class="col-12"><label class="form-label" for="profileFullName">Full name</label><input id="profileFullName" type="text" name="fullname" value="<?php echo htmlspecialchars((string)($user['fullname'] ?? '')); ?>" class="form-control" maxlength="120" required></div><div class="col-12"><label class="form-label" for="profileAvatarFile">Profile picture</label><input id="profileAvatarFile" type="file" name="avatar_file" class="form-control" accept="image/jpeg,image/png,image/gif,image/webp"><div class="form-text">JPG, PNG, GIF, or WebP. Maximum size: 5 MB.</div></div><div class="col-12"><button type="submit" class="btn btn-primary"><i class="fa-solid fa-floppy-disk me-1"></i>Save profile</button></div></form></div></div><div class="card border-0 shadow-sm rounded-4"><div class="card-body p-3 p-md-4"><h2 class="h6 fw-bold mb-3"><i class="fa-solid fa-shield-halved text-primary me-2"></i>Password and security</h2><form action="/user/dashboard#profile" method="POST" class="row g-3" novalidate><input type="hidden" name="csrf" value="<?php echo htmlspecialchars($_SESSION['profile_csrf'] ?? ''); ?>"><input type="hidden" name="action" value="update_password"><div class="col-12"><label class="form-label" for="currentPassword">Current password</label><input id="currentPassword" type="password" name="current_password" class="form-control" autocomplete="current-password" required></div><div class="col-12 col-md-6"><label class="form-label" for="newPassword">New password</label><input id="newPassword" type="password" name="new_password" class="form-control" minlength="8" autocomplete="new-password" required></div><div class="col-12 col-md-6"><label class="form-label" for="confirmPassword">Confirm password</label><input id="confirmPassword" type="password" name="confirm_password" class="form-control" minlength="8" autocomplete="new-password" required></div><div class="col-12"><button type="submit" class="btn btn-outline-primary">Update password</button></div></form></div></div></div>
  </div>
</div>
<script>
/* Preview the selected image immediately without uploading it to the server. */
document.getElementById('profileAvatarFile')?.addEventListener('change', function(){ const file=this.files?.[0]; if(!file)return; const reader=new FileReader(); reader.onload=e=>{document.getElementById('profileAvatarPreview').innerHTML='<img src="'+e.target.result+'" class="rounded-circle object-fit-cover" style="width:128px;height:128px" alt="Selected profile picture">';}; reader.readAsDataURL(file); });
</script>
